image: cypress/browsers:node18.12.0-chrome107-ff106

stages:
  - test

cache:
  paths:
    - node_modules/
    - .npm/

install_dependencies:
  stage: test
  script:
    - npm ci

cypress_tests:
  stage: test
  script:
    - npm run demo:run
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 week
